# Python package

# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  name: Default

#strategy:
 # matrix:
  #  Python27:
   #   python.version: '2.7'
    #Python35:
     # python.version: '3.5'
    #Python36:
     # python.version: '3.6'
    #Python37:
     # python.version: '3.7'

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      color a
      echo Testing
      exit 0
  displayName: 'CMD Testing Stuff'
#- script: |
 #   python -m a=1
 #   a+a
#    print(a)
#  displayName: 'Install dependencies'

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'C:\Users\matth\OneDrive\Desktop\temp.py'
  displayName: 'Creating file in desktop'
